apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: linkyard
spec:
  interval: 30m
  url: https://nexus.linkyard.ch/repository/linkard-helm
  secretRef:
    name: linkyard-nexus-credentials
