apiVersion: v1
kind: Secret
metadata:
    name: linkyard-nexus-credentials
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:WbhZPW5MoQx9xjz/OGoRqA==,iv:yOyPbkLES173fQ5nBYkIYz73KsqU514iZREvm1GEf6Q=,tag:8LL48mlyzHbC3Q74uSo42w==,type:str]
    password: ENC[AES256_GCM,data:Y/NZhI9WPXfrN+U2qxdbLi525bX4ZPoOOTeoIbufNsz4gjWufa6ysjuXVaeZZ+vGVt70N1uyl0o=,iv:/7befMsC2Ej9PtL10B8jnNZCZFnHoR9LN4E5cO87MhM=,tag:pCfbneXvaXLCL/xu2PejRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-01-25T19:58:29Z'
    mac: ENC[AES256_GCM,data:3Mf9MkhXK32FuOlSeE+u+GVfeiZ0NOqE6wtC1qsjAxO0rrdp/AXFXzQRloLRPYQixa6iAcOoFisYguti6IXAU6h/HZpG7bhkvhdvHwAIGXtXXb316KhsOK9bkgftSJ3GedB4IWJIcER5KZQDOeKrJ19/zZ+Z1ndkojx0pwn5/9U=,iv:NA5XMP391PthZs9rMkqABtGfkf9jZXOwUjRUrZ2O5sA=,tag:FDWN2s35FfgqxRKfruy1QQ==,type:str]
    pgp:
    -   created_at: '2021-01-25T19:58:28Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2TMigm2cVBjARAAz0rndEIhyAzUUcJ8A1V6lv35c48BGzUfD+aK/sn2S9QM
            NDlqMbZr9JN/HW2SQ6kgLTuQ1vJSgYL9wXIolYqaXjAOtvsO83KmK0EzWB/4Wd1R
            CqBHWma9Gd1kMytXUWbmSxjA4iZ0eRXysaPxD7wLuyZlNfN1YNQiyS23Jn1J/mXR
            Bq627cXQx9RkNNYoUAOBbWMYREdagvkkNtMAj/0LNzQgH/OEd3j3XhhXEKOXjiAH
            gO+fYBn5SHm8/VDrbZocpDVsLd8Er/mIyoXyj02wW23PSwGy2KyNUehx2dtlRHvx
            7hYViVXHu+OQa1L3aFRpCHv+4SJ1rKhTdbr5P0sVEyM1mkWVTtxIdHc/OVEhH/h+
            xb5xgJJqLCgfrlkAQJUO1rWtb92IXBIs3d18yK5CLbV+LzSc5AjtToYWm98/4/e1
            9pld3ZX5C1ZAkFTiH+zBGg1YlEdcZ6aK0X5g0k1fDWRQnIT/uKT3LcOtBYNfXezP
            PM7R0pil+1QoLmbBYxYNcTsmwPSqRrjFpry5wMG4NOepQFWbfT3axX1JarFigNhV
            0SQwEcuTbkv3EhNqTWFKVP9l7q05vb9uBxpD9IGwzETEc3vNGbHXwxMejrYyGgON
            vGgOIDmbd6cZwO/JCx8NmkIl5bcT3hZj7nbXWQZSwXf7C1z8fQ1Rxzwphi5WerDS
            UQH8RIAuPfvd6DyPNSmAlkrXJVPakSp919eW6WoTDLjRvAEFF1soeCCudNA/lBYu
            Wg5CRp7wXnv5MJNCe8G00SSvmY8wE81vLXaZKZBB/AAqmg==
            =hm0t
            -----END PGP MESSAGE-----
        fp: 0562B9DB934F42095102C9207B8B60141EDF8F92
    -   created_at: '2021-01-25T19:58:28Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3v5uThyFv71ARAAs/hI/aVH6pzANWFYyzmjYVGbOM9SScat/f3q6rN/ovoe
            +r8tApKNZ5AFDHXRiH7MrcauNrwB2IQTzLsbbcKeFmWjWUJnjeJUXopEUR2yb64b
            vkAtPhzFDG0OIHg6BfU8xdoYukB+nC5xKdcTCOjPGf3GkD6x4FpOGB84xw1MR70e
            eydMZpg164XBpcY2zMWz7TkSvv6d+PSjzTOyOrcmK+Tl87Qj998DSvenZ8B74lsR
            qEPl+vE5wruayncI7G/9dnDXaaU6crK6GGzQxjWVNttwxZ6ESqZ18i7bKNgP0NeF
            Enw8NvOlKzKoro7QA6ULsYpWq003ti2ZA5Gp/Y6W9hGdTyeutUCPmE4ZzejtSMR5
            FSlEQilo7fRQUHY3ZChQZC30Ei/BAWLm53r13DOh+eT0hSsqJqwAGZBoCiJZ11hs
            cBwpUipZ1/iRpiorqQEYyLtqPgS+39uKJ6PuMLynGR6SiSyrD5t90FIdF1nQw/+l
            dFFgEdT0vg1MjDQpa6YLvNuYkt/XzjBgv/amtgRWZJ8YQbY8hcQ18wPnphgDi0D/
            tvmeGSzMArginYH5Qb1Ya4OT0AymnUkCiPyqqQh/NKg/m+EOo/mvoR9vFTayBTo5
            6+CAW3D8qzGqdZ2Z+I4Zg/uDHX8+BOVNX4H1pFePK4wPQnaSpJhvzjWKHq/0qHLS
            XgGu/h3MPmMrPGST30N3sOgflOHJkQNYUGhERboCMgpVzodlIDBVtDdrRM/kzWX1
            QBQYIYsj0t4XAdwVS2kIFQVknU9GNbL91BHLR4oS9SEpn/VN2qppF/c5qpU+nVI=
            =b+q2
            -----END PGP MESSAGE-----
        fp: F171E4B4D88C5529037441803B0209C1F59B714E
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
