apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: default-backend
spec:
  releaseName: linkyard-default-backend
  chart:
    spec:
      chart: default-backend
      sourceRef:
        kind: HelmRepository
        name: linkyard
        namespace: flux-system
      version: "211"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
